# Generated by Django 5.2.7 on 2025-10-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_rename_full_name_employee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='full_name',
        ),
    ]
