# Generated by Django 5.2.7 on 2025-10-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_rename_name_employee_full_name'),
        ('employeeapp', '0003_user'),
    ]

    operations = [
    ]
