# Generated by Django 5.2.7 on 2025-10-22 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0006_end_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='end_client',
            new_name='EndClientDetails',
        ),
    ]
