# Generated by Django 5.2.7 on 2025-10-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0008_passtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passtype',
            name='name',
            field=models.CharField(max_length=225),
        ),
    ]
