# Generated by Django 5.2.7 on 2025-10-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0009_alter_passtype_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EndClientDetails',
        ),
        migrations.DeleteModel(
            name='MainAccount',
        ),
    ]
