# Generated by Django 5.2.7 on 2025-10-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0010_delete_endclientdetails_delete_mainaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='endclient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mainclient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
